"""German regions/cities with their Kleinanzeigen URL slugs."""

REGIONS: list[dict] = [
    {"label": "Ganz Deutschland", "slug": ""},
    # Bundesländer
    {"label": "Baden-Württemberg", "slug": "baden-wuerttemberg"},
    {"label": "Bayern", "slug": "bayern"},
    {"label": "Berlin", "slug": "berlin"},
    {"label": "Brandenburg", "slug": "brandenburg"},
    {"label": "Bremen", "slug": "bremen"},
    {"label": "Hamburg", "slug": "hamburg"},
    {"label": "Hessen", "slug": "hessen"},
    {"label": "Mecklenburg-Vorpommern", "slug": "mecklenburg-vorpommern"},
    {"label": "Niedersachsen", "slug": "niedersachsen"},
    {"label": "Nordrhein-Westfalen", "slug": "nordrhein-westfalen"},
    {"label": "Rheinland-Pfalz", "slug": "rheinland-pfalz"},
    {"label": "Saarland", "slug": "saarland"},
    {"label": "Sachsen", "slug": "sachsen"},
    {"label": "Sachsen-Anhalt", "slug": "sachsen-anhalt"},
    {"label": "Schleswig-Holstein", "slug": "schleswig-holstein"},
    {"label": "Thüringen", "slug": "thueringen"},
    # Großstädte
    {"label": "Berlin (Stadt)", "slug": "s-berlin"},
    {"label": "Hamburg (Stadt)", "slug": "s-hamburg"},
    {"label": "München", "slug": "s-muenchen"},
    {"label": "Köln", "slug": "s-koeln"},
    {"label": "Frankfurt am Main", "slug": "s-frankfurt-am-main"},
    {"label": "Stuttgart", "slug": "s-stuttgart"},
    {"label": "Düsseldorf", "slug": "s-duesseldorf"},
    {"label": "Dortmund", "slug": "s-dortmund"},
    {"label": "Essen", "slug": "s-essen"},
    {"label": "Leipzig", "slug": "s-leipzig"},
    {"label": "Bremen (Stadt)", "slug": "s-bremen"},
    {"label": "Dresden", "slug": "s-dresden"},
    {"label": "Hannover", "slug": "s-hannover"},
    {"label": "Nürnberg", "slug": "s-nuernberg"},
    {"label": "Duisburg", "slug": "s-duisburg"},
    {"label": "Bochum", "slug": "s-bochum"},
    {"label": "Wuppertal", "slug": "s-wuppertal"},
    {"label": "Bielefeld", "slug": "s-bielefeld"},
    {"label": "Bonn", "slug": "s-bonn"},
    {"label": "Münster", "slug": "s-muenster"},
    {"label": "Karlsruhe", "slug": "s-karlsruhe"},
    {"label": "Mannheim", "slug": "s-mannheim"},
    {"label": "Augsburg", "slug": "s-augsburg"},
    {"label": "Wiesbaden", "slug": "s-wiesbaden"},
    {"label": "Mönchengladbach", "slug": "s-moenchengladbach"},
    {"label": "Gelsenkirchen", "slug": "s-gelsenkirchen"},
    {"label": "Aachen", "slug": "s-aachen"},
    {"label": "Braunschweig", "slug": "s-braunschweig"},
    {"label": "Chemnitz", "slug": "s-chemnitz"},
    {"label": "Halle (Saale)", "slug": "s-halle-saale"},
    {"label": "Kiel", "slug": "s-kiel"},
    {"label": "Magdeburg", "slug": "s-magdeburg"},
    {"label": "Freiburg im Breisgau", "slug": "s-freiburg-im-breisgau"},
    {"label": "Krefeld", "slug": "s-krefeld"},
    {"label": "Lübeck", "slug": "s-luebeck"},
    {"label": "Oberhausen", "slug": "s-oberhausen"},
    {"label": "Erfurt", "slug": "s-erfurt"},
    {"label": "Mainz", "slug": "s-mainz"},
    {"label": "Rostock", "slug": "s-rostock"},
    {"label": "Kassel", "slug": "s-kassel"},
    {"label": "Saarbrücken", "slug": "s-saarbruecken"},
    {"label": "Potsdam", "slug": "s-potsdam"},
]

REGION_MAP: dict[str, str] = {r["slug"]: r["label"] for r in REGIONS}
